on: [push, pull_request]
name: Benchmark
jobs:
  Build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: ['1.23.x']
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: 'postgres:latest'
        ports:
          - '5432:5432'
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v4
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build Benchmarker
      run: go build main.go
    - name: Run Benchmarker
      run: ./main -source="host=localhost user=postgres password=postgres dbname=test sslmode=disable" -orm=all -debug=false